version: '3.8'

services:
  frontend:
    build: ./frontend  # строим из директории frontend
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://backend:8000
    depends_on:
      - backend
    volumes:
      - ./frontend:/app  # для hot reload в development
      - /app/node_modules

  backend:
    build: ./backend    # строим из директории backend
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://user:password@db/hoopstat_db
    depends_on:
      - db
    volumes:
      - ./backend:/app  # для hot reload

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: hoopstat_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: